language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - master

script:
  - ./scripts/go.test.sh
  - go build -v ./cmd/example-server

after_script:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
