language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master

env:
  - GO111MODULE=on

script:
  - ./scripts/go.test.sh
  - go build -v ./cmd/example-server

after_script:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
